version: "3"

services:
  db:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    restart: always

networks:
  default:
    external:
      name: local-network
