AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 300

Resources:
  CollectLiversFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin
      Handler: collect_livers
      Runtime: go1.x
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Environment:
        Variables:
          STAGE: production
          AWS_REGION: ap-northeast-1
          AWS_ENDPOINT: ""
